In [ ]:
import pandas as pd
import sqlite3
import numpy as np

with sqlite3.connect('data/chamados.db') as conexao:
    query = 'SELECT * FROM chamados'
    df = pd.read_sql_query(query,conexao)

display(df)
display(df.info())
display(df.describe())

In [62]:
#analise
#qual plano mais vende
df_planos = df.groupby('plano')['mensalidade'].sum().sort_values(ascending=False).reset_index()
#quantia de clientes por plano
df_clientes_plano = df.groupby('plano').size().sort_values(ascending=False).reset_index(name='quantia de clientes')
#quantia de inadinplentes
df_inadinplencia = df.groupby(['plano','inadinplencia']).size().unstack(fill_value=0)
#consumo de internet entre clientes ativos e inativos
df_consumo = df.groupby('status')['consumo_Gb'].mean().reset_index()
#estados mais inadimplentes
df_estados_inadimplentes = df.groupby(['estado','inadinplencia']).size().sort_values(ascending=False).unstack(fill_value=0)
#desperdicio de banda
df_desperdicio = df.groupby('plano')['consumo_Gb'].agg(['min','max']).reset_index()
display(df_planos)
display(df_clientes_plano)
display(df_inadinplencia)
display(df_consumo)
display(df_estados_inadimplentes)
display(df_desperdicio)

     plano  mensalidade
0     plus      1587360
1  premium       807480
2   basico       465990

     plano  quantia de clientes
0  premium                 6729
1   basico                 6657
2     plus                 6614

inadinplencia   não   sim
plano
basico         4838  1819
plus           4825  1789
premium        4941  1788

    status  consumo_Gb
0    ativo  116.088823
1  inativo  119.126673

inadinplencia    não   sim
estado
Minas Gerais    4884  1735
Rio De Janeiro  4854  1799
São Paulo       4866  1862

     plano  min  max
0   basico   15   40
1     plus  150  350
2  premium   50  100